-- 0014_seed_applications.sql
-- Seeds the admin applications tracker from BB's tracker.xlsx.
-- Idempotent upsert: updates status/notes/etc on existing ids, never clobbers uploaded *_key document columns.
-- Run remotely:
--   wrangler d1 execute broadnaxux-content --remote --file=cloudflare/migrations/0014_seed_applications.sql

INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('trainual-sr-ai-product-designer','Trainual','Senior AI Product Designer',NULL,'https://careers.kula.ai/trainual/27547/?source=linkedin','LinkedIn','in_progress','AI-forward culture, Tempe location (local), interesting product (training/onboarding UX), comp + small craft team','Hybrid Tempe 3+ days/week. Reports to Liz Dube (VP PD). Peer: Colin Baker (Lead Designer). Small team.','$140,000 – $170,000',NULL,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('vercel-sr-product-designer','Vercel','Senior Product Designer',NULL,'https://job-boards.greenhouse.io/vercel/jobs/5735407004','LinkedIn','applied','Dev-tooling / agentic infra; design systems + code prototyping (v0, Cursor, Claude Code)','Submitted Jun 8 2026. Remote (US); SF/NY/London/Berlin anchor days if local.','$156,000 – $234,000',1780876800,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('weedmaps-sr-product-designer','Weedmaps','Senior Product Designer',NULL,'https://job-boards.greenhouse.io/weedmaps77/jobs/8515259002','LinkedIn','applied','Principal-level IC; design strategy, systems, mission-driven','Submitted Jun 8 2026. Remote. Asks 9-12+ yrs (stretch on years).','$130,386 – $163,606',1780876800,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('teleport-sr-product-designer','Teleport','Senior Product Designer',NULL,'https://jobs.ashbyhq.com/goteleport/d5eb4352-e857-4678-bcc1-ae176882afb6','LinkedIn','applied','Infra / security identity; data-dense UIs, engineer partnership','Submitted Jun 8 2026. Remote-first. Take-home design challenge in process.','Not listed',1780876800,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('ford-sr-ui-product-designer','Ford','Senior UI Product Designer',NULL,'https://www.careers.ford.com/en/job/-/-/48560/94789722016','LinkedIn','applied','Leadership / mentoring, accessibility, service design','Submitted Jun 8 2026. Remote (US). No visa sponsorship.','$115,000 – $192,900',1780876800,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('paylocity-sr-product-designer','Paylocity','Senior Product Designer',NULL,'https://2000recruiting.paylocity.com/Recruiting/Jobs/Details/44978','LinkedIn','applied','Enterprise HCM SaaS; design-system strategy, workflows','Submitted Jun 8 2026. Fully remote (US).','$120,000 – $172,000',1780876800,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('marriott-flex-sr-designer','Marriott','FLEX Senior Designer, Digital Communications',NULL,'https://careers.marriott.com/flex-senior-designer-digital-communications/job/0F49F4909B67DA25CC66861A6D586504','LinkedIn','applied','Email / template design; brand + responsive systems','Submitted Jun 9, 2026. ON HOLD - not submitted. Temporary/contract FLEX (email-focused). Docs ready. JD expires 06/10/2026.','$48.26 – $75.81 / hr',1780876800,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('pinterest-product-designer-ii','Pinterest','Product Designer II, Pinner Actionability',NULL,'https://www.pinterestcareers.com/jobs/7698212/product-designer-ii-pinner-actionability/','LinkedIn','applied','Growth/conversion design, fast experimentation, AI-in-design','Submitted Jun 9, 2026. Docs ready, not yet submitted. Role is ''II'' (2+ yrs) - she''s overqualified but valid. Remote.','$109,242 – $224,910',1780963200,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('babylist-sr-product-designer','Babylist','Senior Product Designer (Registry)',NULL,'https://job-boards.greenhouse.io/babylist/jobs/5823125004','LinkedIn','applied','Consumer e-comm, two-sided marketplace, native+web, AI-forward','Submitted Jun 9, 2026. Docs ready, not yet submitted. Strong fit. Remote US/Canada. 5+ yrs.','$178,035 – $213,725',1780963200,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('jerry-sr-product-designer','Jerry.ai','Senior Product Designer',NULL,'https://jobs.ashbyhq.com/Jerry.ai/e6f3914e-ecd8-46f8-9157-271f315caf5f','LinkedIn','applied','Data-dense consumer app (insurance/fintech); data-to-clarity','Submitted Jun 9, 2026. Docs ready, not yet submitted. JD was JS-rendered; tailored from summary.','Not listed',1780963200,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('anthropic-design-engineer-web','Anthropic','Design Engineer, Web',NULL,'https://job-boards.greenhouse.io/anthropic/jobs/5223916008','LinkedIn','in_progress','Design+code hybrid (Creative Studio brand web); React/CSS/CMS','NOT APPLYING to the Design Engineer role (skill mismatch). BB watching for better-matched Anthropic roles.','$260,000 – $305,000',NULL,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('unframe-ai-product-manager','Unframe','AI Product Manager',NULL,'https://job-boards.eu.greenhouse.io/unframe/jobs/4890170101','LinkedIn','applied','Enterprise LLM apps to production; specs + prompt/context','Submitted Jun 9, 2026. Docs ready, not yet submitted. AI-PM framing. SF / West Coast remote. 6+ yrs.','Not listed',1780963200,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('epiq-ai-sr-product-manager','Epiq','AI Senior Product Manager',NULL,'https://epiqsystems.wd503.myworkdayjobs.com/Epiq_Careers/job/New-York-NY/AI-Senior-Product-Manager_R0034408','LinkedIn','applied','AI PM in e-discovery legal tech - matches her IPRO years','Submitted Jun 9, 2026. Docs ready, not yet submitted. STRONG fit. Remote. 5+ yrs PM, 2+ AI/ML.','$115,000 – $185,000',1780963200,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('motorola-ai-application-specialist','Motorola Solutions','AI Application Specialist',NULL,'https://motorolasolutions.wd5.myworkdayjobs.com/en-US/Careers/job/Texas-Remote-Work/AI-Application-Specialist_R64508','LinkedIn','applied','Applied AI: prompt eng, agent build, SOP workshops, 911/mission-critical','Submitted Jun 9, 2026. Docs ready, not yet submitted. Skill match strong; comp is IC-specialist level. Remote TX. CJIS background check.','$85,000 – $95,000',1780963200,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('bestegg-sr-product-designer','Best Egg','Senior Product Designer (Servicing)',NULL,'https://jobs.lever.co/BestEgg/149eb824-9a6c-4aaa-b0e5-12a81f4b8d50','LinkedIn','applied','Fintech servicing: bill pay, account mgmt, UX content, clarity/trust','Submitted Jun 9, 2026. Docs ready, not submitted. Remote (Wilmington DE). 3-5+ yrs; framed senior. JD via Apify.','$120,000 – $150,000',1780963200,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('supercom-sr-product-designer-credit','Super.com','Senior Product Designer, Credit Building',NULL,'https://jobs.ashbyhq.com/super.com/e7722dfa-4079-43b3-b2f3-fdfe8da754e3','LinkedIn','applied','Fintech 0-1 consumer; AI rapid prototyping; Figma mastery','Submitted Jun 9, 2026. Docs ready, not submitted. Remote-first. 5+ yrs. JD via Apify.','Not listed (equity + competitive)',1780963200,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('transamerica-sr-ux-designer','Transamerica (Aegon)','Senior Digital Experience Specialist / Sr UX Designer',NULL,'https://www.aegon.com/careers/vacancies/united-states/denver/sales-and-marketing/senior-digital-experience-specialist','LinkedIn','applied','Financial services UX design/research/production; accessibility','Submitted Jun 9, 2026. Docs ready, not submitted. HYBRID 3 days/week in hub (Denver) - she''s Phoenix, no relo. Flag. JD via Apify.','$97,000 – $125,000',1780963200,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('wells-fargo-sr-product-designer','Wells Fargo','Senior Product Designer, Fraud and Claims',NULL,'https://www.wellsfargojobs.com/en/jobs/r-539893/senior-product-designer-fraud-and-claims/','LinkedIn','in_progress','Regulated enterprise design, fraud/claims domain; parallels to IPRO compliance work','Docs ready, not yet submitted. Hybrid Chandler AZ (3 days/wk). Closes Jun 15, 2026. IPRO compliance + Alaska DOT = strong fit.','Not listed',NULL,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('arrivia-sr-product-designer','arrivia','Senior Product Designer',NULL,'https://recruiting.ultipro.com/INT1043EXCUR/JobBoard/ad5e5978-552f-4ef7-90c8-70ebb0a57994/OpportunityDetail?opportunityId=ce2e02c4-eb2b-4354-b072-db24973e8b1d','LinkedIn','in_progress','Consumer B2C travel loyalty; AI tooling (Claude/ChatGPT/Gemini named in JD); white-label design systems','Docs ready, not yet submitted. Scottsdale AZ (on-site or hybrid expected). Travel loyalty = direct Alaska overlap. AI tools named explicitly in JD.','Not listed',NULL,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('hudl-sr-ux-designer','Hudl','Senior User Experience Designer',NULL,'https://job-boards.greenhouse.io/hudl/jobs/7899134','LinkedIn','in_progress','Sports tech tools; IC UX ownership, research + delivery, cross-functional; strong comp range','Docs ready, not yet submitted. Remote (Phoenix AZ). $112K-$187K. Research + delivery framing. Strong IC fit.','$112,000 – $187,000',NULL,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('banner-health-sr-accessibility-pm','Banner Health','Senior Digital Product Design, Accessibility Program Manager',NULL,'https://bannerhealth.wd108.myworkdayjobs.com/Careers/job/Remote-Arizona/Senior-Digital-Product-Design-Accessibility-Program-Manager_R4439649','LinkedIn','in_progress','Accessibility program leadership (WCAG/508/VPAT) - MTRCD is a perfect proof point','Docs ready, not submitted. STRONG fit. Remote (AZ eligible). 4+ yrs, 2+ leadership. Closes ~2026-09-30.','$50.12 – $83.54 / hr',NULL,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
INSERT INTO applications (id,company,role,location,jd_url,source,status,fit_notes,notes,salary,applied_at,created_at,updated_at) VALUES ('drivetime-ux-designer-gofi','DriveTime (GoFi)','UX Designer, GoFi',NULL,'https://jobs.drivetime.com/ux-designer-gofi/job/D92C4CFC5F26597DA9842D2A4C726E9E','LinkedIn','in_progress','Auto-finance fintech UX; end-to-end journeys, conversion, accessibility','Docs ready, not submitted. OVERQUALIFIED (role is 1-3 yrs, marketing-leaning). Hybrid 3 days Tempe (commutable from Phoenix).','Not listed',NULL,1781154205,1781154205)
ON CONFLICT(id) DO UPDATE SET company=excluded.company, role=excluded.role, jd_url=excluded.jd_url, source=excluded.source, status=excluded.status, fit_notes=excluded.fit_notes, notes=excluded.notes, salary=excluded.salary, applied_at=excluded.applied_at, updated_at=excluded.updated_at;
